=== statisticsnorway/sms-linkmobility-jaxb/src/main/resources/dtd/pswincom_submit.dtd
<!-- PSWinCom DTD SMS Submit-->
<!ELEMENT ID (#PCDATA)>
<!ELEMENT NET (#PCDATA)>
<!ELEMENT AP (#PCDATA)>
<!ELEMENT SD (#PCDATA)>
<!ELEMENT TEXT (#PCDATA)>
<!ELEMENT CLASS (#PCDATA)>
<!ELEMENT OP (#PCDATA)>
<!ELEMENT RCPREQ (#PCDATA)>
<!ELEMENT RCPFMT (#PCDATA)>
<!ELEMENT SND (#PCDATA)>
<!ELEMENT RCV (#PCDATA)>
<!ELEMENT CLIENT (#PCDATA)>
<!ELEMENT TARIFF (#PCDATA)>
<!ELEMENT PW (#PCDATA)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT TTL (#PCDATA)>
<!ELEMENT CPATAG (#PCDATA)>
<!ELEMENT AGELIMIT (#PCDATA)>
<!ELEMENT SHORTCODE (#PCDATA)>
<!ELEMENT REPLACE (#PCDATA)>
<!ELEMENT DELIVERYTIME (#PCDATA)>
<!ELEMENT SERVICECODE (#PCDATA)>
<!ELEMENT MSG (ID?, NET?, TARIFF?, TEXT, CLASS?, OP?,
RCPREQ?, RCPFRM?, SND?, RCV, TTL?, CPATAG?, AGELIMIT?,
SHORTCODE?, REPLACE?, DELIVERYTIME?, SERVICECODE?)>
<!ELEMENT QRY (NAME)>
<!ELEMENT MSGLST (MSG+)>
<!ELEMENT QRYLST (QRY+)>
<!ELEMENT SESSION (CLIENT, PW, AP?, SD?, MSGLST?, QRYLST?)>

=== statisticsnorway/sms-linkmobility-jaxb/src/test/resources/request.xml
<?xml version="1.0"?>
<!DOCTYPE SESSION SYSTEM "pswincom_submit.dtd">
<SESSION>
    <CLIENT>demo</CLIENT>
    <PW>password</PW>
    <MSGLST>
        <MSG>
            <TEXT>Test message1</TEXT>
            <RCV>4793000000</RCV>
        </MSG>
        <MSG>
            <TEXT>Test message2</TEXT>
            <RCV>4793000000</RCV>
        </MSG>
    </MSGLST>
</SESSION>
